/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacevisual;

import javax.swing.JOptionPane;

/**
 *
 * @author 929688
 */
public class AtividadePlanetas extends javax.swing.JFrame {

    /**
     * Creates new form AtividadePlanetas
     */
    public AtividadePlanetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPeso = new javax.swing.JLabel();
        txfPesoSelecionado = new javax.swing.JTextField();
        cbPlanetas = new javax.swing.JComboBox<>();
        btnCalcularPeso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtPeso.setText("Peso da terra (Kg):");

        txfPesoSelecionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPesoSelecionadoActionPerformed(evt);
            }
        });

        cbPlanetas.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        cbPlanetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mercúrio", "Vênus", "Terra", "Marte", "Júpiter", "Saturno", "Urano", "Netuno", "Lua" }));
        cbPlanetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlanetasActionPerformed(evt);
            }
        });

        btnCalcularPeso.setText("Calcular Peso");
        btnCalcularPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPeso)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfPesoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbPlanetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnCalcularPeso)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(txtPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfPesoSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPlanetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnCalcularPeso)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfPesoSelecionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPesoSelecionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPesoSelecionadoActionPerformed

    private void btnCalcularPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPesoActionPerformed

        double gravidade = 0;
        double resultado;

        double peso = Double.parseDouble(txtPeso.getText());

        String Planetas;
        Planetas = cbPlanetas.getSelectedItem().toString();

        switch(Planetas){
            case "Mercúrio":
                gravidade = 3.6;
                break;
            case "Vênus":
                gravidade = 8.7;
                break;
            case "Terra":
                gravidade = 9.8;
                break;
            case "Marte":
                gravidade = 3.7;
                break;
            case "Júpiter":
                gravidade = 24.79;
                break;
            case "Saturno":
                gravidade = 10.44;
                break;
            case "Urano":
                gravidade = 8.69;
                break;
            case "Netuno":
                gravidade = 11.15;
                break;
            case "Lua":
                gravidade = 1.6;
                break;
        }

        resultado = (peso / 10)*gravidade;
        JOptionPane.showMessageDialog(null, resultado);
    }//GEN-LAST:event_btnCalcularPesoActionPerformed

    private void cbPlanetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlanetasActionPerformed

    }//GEN-LAST:event_cbPlanetasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtividadePlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtividadePlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtividadePlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtividadePlanetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AtividadePlanetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularPeso;
    private javax.swing.JComboBox<String> cbPlanetas;
    private javax.swing.JTextField txfPesoSelecionado;
    private javax.swing.JLabel txtPeso;
    // End of variables declaration//GEN-END:variables
}
